apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.4.3
    helm:
      valueFiles:
      - $values/values/kafka.yaml
  - repoURL: https://github.com/Kimjibeom/argocd-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
