apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.110
    helm:
      valueFiles:
      - $values/values/jenkins.yaml
  - repoURL: https://github.com/Kimjibeom/argocd-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
