apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-db
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.2.3
    helm:
      valueFiles:
      - $values/values/mlflow-db.yaml
  - repoURL: https://github.com/Kimjibeom/argocd-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
