apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://cagataygurturk.github.io/helm-microservices/
    chart: n8n
    targetRevision: 1.16.29
    helm:
      valueFiles:
      - $values/values/n8n.yaml
  - repoURL: https://github.com/Kimjibeom/argocd-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
